<?php

namespace App\Filament\Resources\AdherantResource\Pages;

use App\Filament\Resources\AdherantResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditAdherant extends EditRecord
{
    protected static string $resource = AdherantResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\ViewAction::make(),
            Actions\DeleteAction::make(),
        ];
    }

//    protected function mutateFormDataBeforeSave(array $data): array
//    {
//        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
//    }
}
