<?php

namespace App\Filament\Resources\RoleCommuneResource\Pages;

use App\Filament\Resources\RoleCommuneResource;
use App\Models\RoleCommune;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateRoleCommune extends CreateRecord
{
    protected static string $resource = RoleCommuneResource::class;


//    protected function mutateFormDataBeforeCreate(array $data): array
//    {
//
//        dd($data);
//
//       return $data;
//    }



    protected function handleRecordCreation(array $data): Model
    {


        foreach ($data['commune_id'] as $key=>$val){
            $yourModel = RoleCommune::create(['role_id'=>$data['role_id'],'commune_id'=>$val]);
        }



//        $yourModel = RoleCommune::create(['role_id'=>$data['role_id'],'commune_id'=>null]);
//        $yourModel->commune()->sync($data['commune_id']);


      return $yourModel;
//        return parent::handleRecordCreation([]); // TODO: Change the autogenerated stub
    }
    protected function getRedirectUrl(): string
    {
        // Rediriger vers la page d'index après la création
        return $this->getResource()::getUrl('index');
    }




//    protected function handleRecordCreation(array $data)
//    {
//        $yourModel = YourModel::create($data);
//
//        // Sync the relationship for multiple communes
//        $yourModel->communes()->sync($data['commune_id']);
//
//        return $yourModel;
//    }


}
